name: build-image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      SCALA_VERSION: 2.13.8
      SBT_VERSION: 1.6.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SBT action test
        id: sbt
        uses: briskware/github-action-sbt@master
        with:
          commands: test
          sbt_project_directory: .
